name: "Check Docs"
# https://github.com/marketplace/actions/sphinx-build

on: # Trigger the workflow on push or pull request, but only for the master branch
  push: {}
  pull_request:
    branches: [master]

jobs:
  make-docs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # Note: This uses an internal pip API and may not always work
    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pandoc
        python --version
        pip --version
        pip install . --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install --requirement requirements/docs.txt
        # install Texlive, see https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
        sudo apt-get update && sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
        pip list
      shell: bash

    - name: Make Documentation
      run: |
        # First run the same pipeline as Read-The-Docs
        cd docs
        make clean
        make html --debug --jobs 2 SPHINXOPTS="-W --keep-going"

    - name: Upload built docs
      uses: actions/upload-artifact@v2
      with:
        name: docs-results-${{ github.sha }}
        path: docs/build/html/
      # Use always() to always run this step to publish test results when there are test failures
      if: success()

  test-docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Note: This uses an internal pip API and may not always work
      # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/base.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake pandoc
          pip install '.[all]' --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install '.[test]' --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install --requirement requirements/docs.txt
          python --version
          pip --version
          pip list
        shell: bash

      - name: Cache datasets
        uses: actions/cache@v3
        with:
          path: |
            docs/data
            data
          key: flash-datasets-docs

      - name: Test Documentation
        env:
          SPHINX_MOCK_REQUIREMENTS: 0
          FIFTYONE_DO_NOT_TRACK: true
        run: |
          # First run the same pipeline as Read-The-Docs
          apt-get update && sudo apt-get install -y cmake
          cd docs
          FLASH_TESTING=1 make doctest
